version: '3'
services: 
  db:
    image: mariadb:10
    ports: 
      - 3306:3306
    environment: 
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    volumes: 
      - db:/var/lib/mysql
volumes: 
  db: