"""add crafting rules and recipes

Revision ID: 2e1fa02cfdf1
Revises: 0b7f16606398
Create Date: 2021-08-29 19:30:22.934329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1fa02cfdf1'
down_revision = '0b7f16606398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crafting_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crafting_rules_name'), 'crafting_rules', ['name'], unique=False)
    op.create_table('crafting_rule_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=512), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['crafting_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crafting_rule_recipes_name'), 'crafting_rule_recipes', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crafting_rule_recipes_name'), table_name='crafting_rule_recipes')
    op.drop_table('crafting_rule_recipes')
    op.drop_index(op.f('ix_crafting_rules_name'), table_name='crafting_rules')
    op.drop_table('crafting_rules')
    # ### end Alembic commands ###
